### ISSUE TITLE
Move navbar to top of page?

### ISSUE THREAD

**Issue by AKhan139** [CollectionBuilder/collectionbuilder.github.io#131]
### Discussed in https://github.com/orgs/CollectionBuilder/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **AKhan139** July 18, 2024</sup>
Hi all! I'm working on a new site using Collection Builder and having a ton of trouble moving the navigation bar to the top of a page, as opposed to being below the main banner image. I've been able to generate a sort of mini-homepage that looks the way i want with the navbar on the top of the page, but this whole thing exists below the current banner image and navigation bar and I can't figure out how to get rid of it/move it below the navigation bar. Any insight is appreciated!</div>

**Comment by AKhan139** [comment]
Link to repo: https://github.com/AKhan139/tracing-medea/

**Comment by evanwill** [comment]
@AKhan139 Discussions is the best place for this question, since you already have the question there, I'm just closing this Issue here!
