### ISSUE TITLE
browse function - view in order

### ISSUE THREAD

**Issue by mshannon95** [CollectionBuilder/collectionbuilder.github.io#15]
Hi,
When I go into a collection in Collection Builder, and I go into the Browse tab, the images are not in numeric order based on Identification Number. Is it possible to add an option to view the images in order based on their Identification Numbers? I understand the randomness can help showcase different facets of the collection and that's fine, but it would also be nice to have an option to view the images in their correct arrangement (a.k.a. the arrangement that reflects their physical arrangement in our physical collections).

Thank you!! - Michelle Shannon

**Comment by dcnb** [comment]
Hi Michelle, The UI digital collections are built with this repository: https://github.com/uidaholib/collectionbuilder-cdm-template/issues

Please add your issue to the issues tab there. This is the repo for the collectionbuilder tool website.
