### ISSUE TITLE
master to main branch

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder.github.io#19]
New repos created on github use `main` rather than `master`. 
github is going to provide tools to migrate old repos to `main` eventually--so I don't think we should migrate the repos until that is out. If you click "use template" folks will still have `master` copied from the template.
however, people creating new repos will have `main` instead. 

our docs mention `master` branch. Should probably swap to `main` \ `master` for now to avoid confusion? 

@owikle @dcnb this applies to the `ala-demo` which has `main` branch.

**Comment by owikle** [comment]
Yeah, probably a good idea to temporarily do main/master
